security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        #asociateyaBundle\Entity\Usuario: plaintext
        asociateyaBundle\Entity\Usuario:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        asociateya_provider:
            entity:
                class: asociateyaBundle:Usuario
                property: nombreUsuario
                #va el nombre del atributo, no de la propiedad
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
#
#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
        registrar:
            pattern:  ^/registrar$
            security: false
        registrarCrear:
            pattern:  ^/registrar/crear$
            security: false
        registrarExito:
            pattern:  ^/registrar/exito$
            security: false
        ingresar:
            pattern:  ^/ingresar$
            security: false
#
#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: _security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        default:
            pattern:    ^/
            http_basic: ~
            provider: asociateya_provider
            #anonymous: ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        
   
