asociateya_usuario:
    resource: "@asociateyaBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

asociateya_emprendedor:
    resource: "@asociateyaBundle/Resources/config/routing/emprendedor.yml"
    prefix:   /emprendedor

desarrollo_federico:
    resource: "@asociateyaBundle/Resources/config/federicoRouting.yml"
    prefix:   /

asociateya_homepage:
    path:     /
    defaults: { _controller: asociateyaBundle:Default:index }

asociateya_formularioModificacionUsuario:
    path:     /modificarUsuario
    defaults: { _controller: asociateyaBundle:UsuarioAnonimo:formularioModificacionUsuario }

asociateya_formularioRegistrarse:
    path:     /registrar
    defaults: { _controller: asociateyaBundle:UsuarioAnonimo:formularioRegistro }

asociateya_registrar:
    path:     /registrar/crear
    defaults: { _controller: asociateyaBundle:UsuarioAnonimo:registrarUsuario }

asociateya_registrar_exito:
    path:     /registrar/exito
    defaults: { _controller: asociateyaBundle:UsuarioAnonimo:exitoRegistro }

asociateya_ingresar:
    path:     /ingresar
    defaults: { _controller: asociateyaBundle:UsuarioAnonimo:ingresar }

asociateya_ingresar_exito:
    path:     /ingresar_exito
    #este path no tiene controller, lo maneja el sistema de seguridad

asociateya_salir:
    path: /salir
    #este path lo maneja el sistema de seguridad