desarrollo_federico:
    resource: "@asociateyaBundle/Resources/config/federicoRouting.yml"
    prefix:   /

asociateya_homepage:
    path:     /
    defaults: { _controller: asociateyaBundle:Default:index }
    
asociateya_formularioRegistrarse:
    path:     /registrar
    defaults: { _controller: asociateyaBundle:UsuarioAnonimo:formularioRegistro }
    
asociateya_registrar:
    path:     /registrar/crear
    defaults: { _controller: asociateyaBundle:UsuarioAnonimo:registrarUsuario }

asociateya_registrar_exito:
    path:     /registrar/exito
    defaults: { _controller: asociateyaBundle:UsuarioAnonimo:exitoRegistro }