emprendimiento:
    path:     /
    defaults: { _controller: "asociateyaBundle:Emprendimiento:index" }

emprendimiento_listado:
    path:     /listado
    defaults: { _controller: "asociateyaBundle:Emprendimiento:listado" }

emprendimiento_busqueda:
    path:     /buscar
    defaults: { _controller: "asociateyaBundle:Emprendimiento:buscar" }

emprendimiento_busquedaPalabra:
    path:     /buscar/palabra
    defaults: { _controller: "asociateyaBundle:Emprendimiento:buscarPalabra" }

emprendimiento_show:
    path:     /{id}/mostrar
    defaults: { _controller: "asociateyaBundle:Emprendimiento:show" }

emprendimiento_new:
    path:     /nuevo
    defaults: { _controller: "asociateyaBundle:Emprendimiento:new" }

emprendimiento_create:
    path:     /crear
    defaults: { _controller: "asociateyaBundle:Emprendimiento:create" }
    methods:  POST

emprendimiento_aprobar:
    path:     /{id}/aprobar
    defaults: { _controller: "asociateyaBundle:Emprendimiento:aprobar" }

emprendimiento_pendientes:
    path:     /pendientes
    defaults: { _controller: "asociateyaBundle:Emprendimiento:pendientes" }

emprendimiento_edit:
    path:     /{id}/editar
    defaults: { _controller: "asociateyaBundle:Emprendimiento:edit" }

emprendimiento_update:
    path:     /{id}/actualizar
    defaults: { _controller: "asociateyaBundle:Emprendimiento:update" }
    methods:  [POST, PUT]

emprendimiento_delete:
    path:     /{id}/eliminar
    defaults: { _controller: "asociateyaBundle:Emprendimiento:delete" }
    methods:  [POST, DELETE]

emprendimiento_comentar:
    path:     /{id}/comentar
    defaults: { _controller: "asociateyaBundle:Emprendimiento:comentar" }
    methods:  POST

emprendimiento_asociarse:
    path:     /{id}/asociarse
    defaults: { _controller: "asociateyaBundle:Emprendimiento:asociarse" }

emprendimiento_confirmarPago:
    path:     /{id}/confirmarPago
    defaults: { _controller: "asociateyaBundle:Emprendimiento:confirmarPago" }

emprendimiento_pagoPendiente:
    path:     /{idInversion}/pagoPendiente
    defaults: { _controller: "asociateyaBundle:Emprendimiento:pagoPendiente" }

emprendimiento_pagoAprobado:
    path:     /pagoAprobado
    defaults: { _controller: "asociateyaBundle:Emprendimiento:pagoAprobado" }

emprendimiento_pagosControl:
    path:     /controlPagos
    defaults: { _controller: "asociateyaBundle:Emprendimiento:pagosControl" }

emprendimiento_confirmarPagoRefund:
    path:     /{id}/confirmarPagoRefund
    defaults: { _controller: "asociateyaBundle:Emprendimiento:confirmarPagoRefund" }

emprendimiento_pagoPendienteRefund:
    path:     /{idEmprendimiento}/pagoPendienteRefund
    defaults: { _controller: "asociateyaBundle:Emprendimiento:pagoPendienteRefund" }