# emprendedor:
#     path:     /
#     defaults: { _controller: "asociateyaBundle:Emprendedor:index" }

# emprendedor_show:
#     path:     /{id}/show
#     defaults: { _controller: "asociateyaBundle:Emprendedor:show" }

emprendedor_new:
    path:     /aplicar
    defaults: { _controller: "asociateyaBundle:Emprendedor:new" }

emprendedor_newExito:
    path:     /aplicar/exito
    defaults: { _controller: "asociateyaBundle:Emprendedor:newExito" }

emprendedor_pendientes:
    path:     /pendientes
    defaults: { _controller: "asociateyaBundle:Emprendedor:pendientes" }

emprendedor_aprobar:
    path:     /{id}/aprobar
    defaults: { _controller: "asociateyaBundle:Emprendedor:aprobar" }

emprendedor_noAprobar:
    path:     /{id}/noAprobar
    defaults: { _controller: "asociateyaBundle:Emprendedor:noAprobar" }


# emprendedor_create:
#     path:     /create
#     defaults: { _controller: "asociateyaBundle:Emprendedor:create" }
#     methods:  POST

# emprendedor_edit:
#     path:     /{id}/edit
#     defaults: { _controller: "asociateyaBundle:Emprendedor:edit" }

# emprendedor_update:
#     path:     /{id}/update
#     defaults: { _controller: "asociateyaBundle:Emprendedor:update" }
#     methods:  [POST, PUT]

# emprendedor_delete:
#     path:     /{id}/delete
#     defaults: { _controller: "asociateyaBundle:Emprendedor:delete" }
#     methods:  [POST, DELETE]
